### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/deephaven-csv#2]
Decision that needs to be made:

Should we use group `io.deephaven`, or `io.deephaven.csv`?

I'm assuming we'll want the artifact name `deephaven-csv`; in which case, `io.deephaven.csv` *may* be a bit redundant. On the other hand, `io.deephaven.csv` provides deephaven-csv (the repo) a bit more leeway in "owning" the full scope of packages under `io.deephaven.csv`.

**Comment by kosak** [comment]
I don't have enough experience with Maven to make an informed comment. My *uninformed* opinion is that we should use io.deephaven.csv due to your "owning" argument.
