### ISSUE TITLE
Specify a "default" parser

### ISSUE THREAD

**Issue by Jolanrensen** [deephaven/deephaven-csv#221]
While we can specify a parser per index or column name, we cannot specify a "default" parser for when we do not know how many columns the file will have or which names the columns will get.

It may be beneficial to be able to call 

```java
.putParserForName("colA", Parsers.DOUBLE)
.defaultParser(Parsers.STRING)
```
which will read the CSV in such a way that `colA` will be parsed using the double parser and all other columns will be parsed as String. This would essentially disable the column type inference.

**Comment by kosak** [comment]
I think this will do what you're asking. Kindly let me know if it works for your use case; it not we can try to provide something.

```
.putParserForName("colA", Parsers.DOUBLE)
.parsers(Collections.singletonList(Parsers.STRING))
```
