### ISSUE TITLE
Tokenizer.tryParseBMPChar returns incorrect results

### ISSUE THREAD

**Issue by kosak** [deephaven/deephaven-csv#70]
`Tokenizer.tryParseBMPChar` is supposed to return true when:

1. the input bytes, interpreted as UTF-8, represent a string that is 1 character in length, and
2. that single character is in the Unicode Basic Multilingual Plane (basically those characters representable by a single Java char)

Unfortunately `Tokenizer.tryParseBMPChar` had a small bug whereby if the first character of a multi-char string was non-ASCII, it would be considered a single char (with the rest of the string thrown away) rather than being considered a multi-character string.

For example the string 穿仓保证金补偿 would unfortunately be parsed as the character 穿.

Reported in https://github.com/deephaven/deephaven-core/issues/2898

**Comment by devinrsmith** [comment]
Fixed by #71
